services:
  webcam:
    build:
      context: face-recog
      dockerfile: Dockerfile-webcam-gpu
    container_name: face_webcam
    ports:
      - "9443:9443"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - "nvidia.com/gpu=all"
    command: python3 webcam.py

  dbutil:
    build:
      context: face-recog
      dockerfile: Dockerfile-dbutil
    container_name: face_dbutil
    ports:
      - "9444:9444"
    command: python3 dbutil.py

  db:
    build: 
      context: database
      dockerfile: Dockerfile
    container_name: oracle_db
    ports:
      - "1521:1521"
