services:
  app:
    build:
      context: face-recog
      dockerfile: Dockerfile
    container_name: face_recognition_app
    ports:
      - "8843:88443"

  db:
    build: 
      context: database
      dockerfile: Dockerfile
    container_name: oracle_db
    ports:
      - "1521:1521"
