services:
  app:
    build:
      context: face-recog
      dockerfile: Dockerfile
    container_name: face_recognition_app
    ports:
      - "8443:8443"
      - "8444:8444"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - "nvidia.com/gpu=all"

  db:
    build: 
      context: database
      dockerfile: Dockerfile
    container_name: oracle_db
    ports:
      - "1521:1521"
