FROM oraclelinux:9

# Install Oracle Instant Client
RUN  dnf -y install oracle-instantclient-release-23ai-el9 && \
     dnf -y install oracle-instantclient-basic oracle-instantclient-devel oracle-instantclient-sqlplus && \
     rm -rf /var/cache/dnf



# Install dependencies
RUN yum install -y \
    python3 \
    python3-pip \
    python3-devel \
    cmake \
    g++ \
    wget \
    unzip \
    mesa-libGL

# Install required packages for video support
RUN yum install -y xterm

# Copy the requirements file
COPY requirements.txt .

# Install the python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
RUN mkdir /app
COPY src/ /app
WORKDIR /app

# Run the application
CMD ["/usr/bin/xterm","-display",":0"]
#CMD ["python3", "/app/capture.py"]