[supervisord]
nodaemon=true

[program:app1]
command=python3 /app/webcam.py
autorestart=true
stdout_logfile=/app/logs/webcam.log
stderr_logfile=/app/logs/webcam.err

[program:app2]
command=python3 /app/dbutil.py
autorestart=true
stdout_logfile=/app/logs/dbutil.log
stderr_logfile=/app/logs/dbutil.err